[bumpver]
current_version = "1.6.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "v{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true

[bumpver.file_patterns]
"CITATION.cff" = [
    'cff-version: {pep440_version}',
]