[bumpver]
current_version = "v1.6.1-cpp"
version_pattern = "v{MAJOR}.{MINOR}.{PATCH}-cpp"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"CITATION.cff" = [
    'version: {pep440_version}',
]