name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - run: ./style.sh

  cpp-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 clang clang-tidy
          python3 -m pip install pip --upgrade
          python3 -m pip install downstream
      - name: Run lint checks
        run: ./lint.sh
      - name: Run C++ syntax checks
        run: make check
      - name: Build and validate tests
        run: make validate