name: CI
on:
  push:
    branches: [ python ]
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:

  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          sudo apt-get update -y
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./style.sh

  requirements:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          sudo apt-get update -y
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./requirements.sh

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./lint.sh

  test-downstream:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: python3 -m pytest -n auto test_downstream

  test-validators:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: python3 -m pip install .
      - run: python3 -m downstream -h
      - run: python3 -m downstream.testing.validate_one 'python3 -m downstream' steady_algo.assign_storage_site
      - run: python3 -m downstream.testing.validate_all 'python3 -m downstream'

  test-packaging:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install '.[testing]'
          rm -rf downstream
      # ignore warnings to reduce memory use
      # (there are a lot of deprecation warnings)
      - run: |
          python3 -m pytest -n auto -W ignore test_downstream

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-bdist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build bdist
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install "setuptools==69.2.0" --upgrade
          python3 setup.py bdist_wheel
          tree dist
          deactivate
      - name: Upgrade pip
        run: python3 -m pip install pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from bdist
        run: python3 -m pip install dist/*.whl
      - name: Test install
        run: |
          find . -type f -name '*.py' -exec rm {} \;
          python3 -c "import downstream; print(downstream.__version__)"

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-sdist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build sdist
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install "setuptools==69.2.0" --upgrade
          python3 setup.py sdist
          tree dist
          deactivate
      - name: Upgrade pip
        run: python3 -m pip install pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from sdist
        run: python3 -m pip install dist/*.tar.gz
      - name: Test install
        run: |
          find . -type f -name '*.py' -exec rm {} \;
          python3 -c "import downstream; print(downstream.__version__)"

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-source:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upgrade pip
        run: python3 -m pip install pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from source
        run: python3 -m pip install .
      - name: Test install
        run: |
          rm -rf *
          cd
          python3 -c "import downstream; print(downstream.__version__)"

  deploy:
    needs:
      - packaging-bdist
      - packaging-sdist
      - packaging-source
      - test-downstream
      - test-packaging
      - test-validators
      - lint
      - style
      - requirements
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade "setuptools==69.2.0"
        python -m pip install -r requirements.txt
    - run: python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
