name: C++ CI
on:
  push:
    branches: [ cpp ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - run: ./style.sh

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      - run: ./lint.sh

  test-validators:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
        mode: [release, debug]
    env:
      CXX: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-13 clang
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - name: Run C++ syntax checks
        run: make check
      - name: Build and validate tests
        run: |
          make clean
          make ${{ matrix.build_mode }}
          make validate