name: C++ CI
on:
  push:
    branches: [ cpp ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - run: ./style.sh

  test-validators:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 clang clang-tidy
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - name: Run lint checks
        run: ./lint.sh
      - name: Run C++ syntax checks
        run: make check
      - name: Build and validate tests, debug mode
        run: |
          make clean
          make debug
          make validate
      - name: Build and validate tests, build mode
        run: |
          make clean
          make build
          make validate
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force