name: C++ CI
on:
  push:
    branches: [ cpp ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - run: ./style.sh

  test-validators:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 clang clang-tidy
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      - name: Run lint checks
        run: ./lint.sh
      - name: Run C++ syntax checks
        run: make check
      - name: Build and validate tests, debug mode
        run: |
          make clean
          make debug
          make validate
      - name: Build and validate tests, build mode
        run: |
          make clean
          make build
          make validate