name: Release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install bumpver
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update cpp version
        working-directory: ./cpp
        run: |
          bumpver update --${{ github.event.inputs.bump_type }}
          version=$(bumpver show -v)
          git tag "v${version}-cpp"
          git push origin "v${version}-cpp"
      - name: Update zig version
        working-directory: ./zig
        run: |
          bumpver update --${{ github.event.inputs.bump_type }}
          version=$(bumpver show -v)
          git tag "v${version}-zig"
          git push origin "v${version}-zig"
      - name: Update csl version
        working-directory: ./csl
        run: |
          bumpver update --${{ github.event.inputs.bump_type }}
          version=$(bumpver show -v)
          git tag "v${version}-csl"
          git push origin "v${version}-csl"
      - name: Update main version
        run: |
          git add .
          git commit -m "Update subrepo versions"

          bumpver update --${{ github.event.inputs.bump_type }}
          version=$(bumpver show -v)

          git tag "v${version}"
          git push origin main
          git push origin "v${version}"
